/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "tertiary-container": "#2d3438",
        "on-background": "#181c1e",
        "surface-container-high": "#e5e9eb",
        "on-primary-fixed": "#001b3c",
        "background": "#f7fafc",
        "error-container": "#ffdad6",
        "on-surface-variant": "#43474f",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d6e3ff",
        "tertiary-fixed": "#dce3e8",
        "on-secondary-container": "#0f4787",
        "surface": "#f7fafc",
        "on-tertiary-fixed-variant": "#41484c",
        "surface-container-highest": "#e0e3e5",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eef1f3",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        "on-surface": "#181c1e",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#799dd6",
        "on-tertiary-container": "#959ca1",
        "surface-container": "#ebeef0",
        "primary": "#001e40",
        "secondary-container": "#8cb7ff",
        "on-primary-fixed-variant": "#1f477b",
        "outline-variant": "#c3c6d1",
        "on-tertiary-fixed": "#161d20",
        "tertiary": "#181f23",
        "surface-dim": "#d7dadc",
        "secondary": "#305ea0",
        "secondary-fixed-dim": "#a9c7ff",
        "outline": "#737780",
        "surface-tint": "#3a5f94",
        "primary-fixed": "#d5e3ff",
        "on-secondary-fixed": "#001b3d",
        "surface-container-low": "#f1f4f6",
        "primary-fixed-dim": "#a7c8ff",
        "on-secondary-fixed-variant": "#0e4686",
        "primary-container": "#003366",
        "surface-bright": "#f7fafc",
        "inverse-primary": "#a7c8ff",
        "tertiary-fixed-dim": "#c0c7cc"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "container-max": "1200px",
        "margin-desktop": "40px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        caption: ["Inter"],
        "title-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
